clear all; close all;

cd E:\U\Ubi_Guger_Data
fname = '20170203_04';
load([fname '.cfg'],'-mat');

[Nch,chnm] = uichannelsettings(fname);
Nch = 35;
itrig = 34;
itrig = strmatch('trig 1',chnm);

fid = fopen([fname '.bin'],'r'); % load data
fseek(fid,0,'eof');
nbytes = ftell(fid); % number of bytes in file
N = nbytes/4/Nch; % number of samples per channel (4 bytes per single-precision sample)
fseek(fid,0,'bof');

% fs_target = 333;
% downsampleby = round(UI.samprate/fs_target); % take every "downsampleby" samples
% fs = UI.samprate/downsampleby;

fseek(fid, (itrig-1)*4, 'bof'); % offset to start of trigger channel
trigdat = fread(fid, N, 'single', 4*(Nch-1));
triggers = find(trigdat/1e3>100); % > 100mV

function [Nch,chnm,chgu] = uichannelsettings(cfgfile)
% function [Nch,chnm,chgu] = uichannelsettings(cfgfile)
%   Read user-interface settings in *.cfg files generated by various
%   gUSBamp programs to determine number and names of channels.
load([cfgfile '.cfg'],'-mat');
Nch = length(find(UI.ch_enabled))+length(find(UI.ga_trigger)); % number of channels
if isfield(UI,'plot_fdb'), Nch = Nch+1; end
if isfield(UI,'plot_fdb') && str2double(cfgfile(end-10:end-3))>=20120202, Nch = Nch+1; end
chnm = cell(Nch,1); % name of channels
chgu = zeros(Nch,1); % gUSBamp that channel was recorded on
ii = 0;
for iga = 1:length(UI.ga_trigger)
    ind = find(UI.ch_enabled(iga,:));
    chnm(ii+1:ii+length(ind)) = UI.ch_name(iga,ind)';
    chgu(ii+1:ii+length(ind)) = iga*ones(length(ind),1);
    ii = ii + length(ind);
    if UI.ga_trigger(iga), chnm{ii+1} = ['trig ' num2str(iga)]; chgu(ii+1) = iga; ii = ii + 1; end
end
if isfield(UI,'plot_fdb'), chnm{ii+1} = 'targets'; chgu(ii+1) = NaN; end
if isfield(UI,'plot_fdb') && str2double(cfgfile(end-10:end-3))>=20120202, chnm{ii+2} = 'reward'; chgu(ii+2) = NaN; end
end